package org.zjubs.pricecomwebbackend;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.ServletComponentScan;
import org.springframework.scheduling.annotation.EnableScheduling;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
//@ServletComponentScan
@SpringBootApplication
@EnableScheduling
public class PriceComWebBackendApplication {

	public static void main(String[] args) {
		SpringApplication.run(PriceComWebBackendApplication.class, args);
	}

}
