spring:
  application:
    name: PriceComWebBackend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/price_compare?allowPublicKeyRetrieval=true&useSSL=false
    password: "zhao1290"

server:
  port: 8082

